# Generated by Django 5.2.16 on 2026-07-22 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Example: First Term', max_length=30)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publications', to='portal.academicsession')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_publications', to='portal.schoolclass')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_session__name', 'school_class__name', 'term'],
                'constraints': [models.UniqueConstraint(fields=('academic_session', 'school_class', 'term'), name='unique_publication_per_session_class_term')],
            },
        ),
    ]
