# Generated by Django 5.2.16 on 2026-07-23 13:03

import django.core.files.storage
import pathlib
import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_resultpublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdocument',
            name='pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/USER/Documents/Projects/Solo Projects/student_result_portal/private_uploads')), upload_to=portal.models.result_upload_path, validators=[portal.models.validate_pdf]),
        ),
    ]
