# Generated by Django 5.2.16 on 2026-07-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_student_gender_alter_resultdocument_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Newsletter Title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('academic_session', models.CharField(help_text='e.g. 2025/2026 ACADEMIC SESSION', max_length=50, verbose_name='Academic Session')),
                ('summary', models.TextField(help_text='Brief summary to display on the dashboard card.')),
                ('body', models.TextField(help_text='Full body content. Paragraphs separated by blank lines will render cleanly.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='newsletters/', verbose_name='Featured Image')),
                ('published', models.BooleanField(default=False, help_text='Tick to publish this newsletter to the portal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
            },
        ),
    ]
